source :gemcutter
gem "rails", "~> 2.1.0"
gem "sqlite3-ruby", :require => "sqlite3"

# bundler requires these gems in all environments
# gem "nokogiri", "1.4.2"
# gem "geokit"

gem "jrails"
gem "wndx-multiselect", :path => '../../'

group :development do
  # bundler requires these gems in development
  # gem "rails-footnotes"
end

group :development, :test do
  # bundler requires these gems while running tests
  gem "rdoc"
  gem "rspec-rails", "~> 1.3"
  gem 'jasmine', "~> 1.0.2"
end
